### PR TITLE
fix serializer regression for Akka.Persistence.MongoDb v1.3.12

### LINKED ISSUE #57: Regression: can't load Akka.Persistence.MongoDb events persisted prior to v1.3.12
Looks like the issue is caused by having a `null` manifest, so we need to test for that and have a fallback.

### PR DESCRIPTION
**Pull request by Aaronontheweb**
close #57

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Adding a spec to verify this

**Comment by jackowild** [comment]
Hi @Aaronontheweb, this doesn't fix the issue I'm afraid. It's line 299 of MongoDbJournal.cs that is causing the problem. It's already dealt with in MongoDbSnapshotStore.cs by checking for null or empty so the same could be applied to this file also?

**Comment by jackowild** [comment]
Yep that's right. Thanks

**Comment by jackowild** [comment]
Cool, what version number will we go with now? 1.3.13?

**Comment by Aaronontheweb** [comment]
Added regression spec - verified failure before my fix and success after

**Pull request merged**
