### PR TITLE
upgrade mongo driver to 2.5.0

### PR DESCRIPTION
**Pull request by maxx1337**
upgrade mongo driver to version 2.5.0

### CODE REVIEW

**Comment by diegolinan** [comment]
@jackowild or anyone, can we merge this one? Seems really useful to have the latest version since it supports the latest versions of mongo plus the fact that it allows you to deserialise immutable classes according to what I saw on the repo...

**Comment by diegolinan** [comment]
Hi guys. So, what's missing to merge with master? The docs seem outdated with the new changes. Need any help with that?

**Comment by jackowild** [comment]
If you could do the docs that would be great. We just need to merge in #28 and your docs PR then I think we're ready to merge to master.

Regarding #28 I just wanted to run the code before completing the PR so leave that to me.

**Comment by diegolinan** [comment]
Ok. I'll need a list of all major breaking changes though. I understand, for instance, that we can remove registering class maps now

**Comment by jackowild** [comment]
I don't think there are any breaking changes? Yes we should add a note stating it is no longer necessary to register class maps.

**Comment by diegolinan** [comment]
So, top of my head, we should add:
 - Supports latest version of akka.persistence
 - Supports latest version of .NET MongoDB Driver
 - Not necessary to register class maps anymore

Comments?

**Comment by diegolinan** [comment]
BTW, I'll do it once the PR for https://github.com/AkkaNetContrib/Akka.Persistence.MongoDB/pull/28 is done if that's ok

**Comment by jackowild** [comment]
So I think there are 2 doc files that need updating:

1. RELEASE_NOTES.md
Remove the 1.3.1 update as nothing was released then.
Under 1.3.5, add your notes from the top of your head. In addition, add .NET Standard 1.6 support.

2. README.md
Under serialization add a note about not needing to register class maps anymore.

**Comment by diegolinan** [comment]
Perfect! Will do as soon as I get out of work and, again, https://github.com/AkkaNetContrib/Akka.Persistence.MongoDB/pull/28 is pushed. Agreed?

**Comment by jackowild** [comment]
Agreed. Looking at #28 now so hopefully will be done soon.

**Comment by jackowild** [comment]
Ok, good to go!

**Comment by diegolinan** [comment]
Should we also pull out of beta at this point? Seems to me we are quite stable

**Comment by diegolinan** [comment]
So, I'm done guys... Any chance to push to master?

**Pull request merged**
