### PR TITLE
Full Type Name + Assembly name in the object discriminator

### PR DESCRIPTION
**Pull request by spankr**
Overrides MongoDB's default Object serializer with an extended one that injects a customized discriminator.

For example, Snapshot objects used to be persisted as:

```
{
        "_t": "MyInternalState",
        "Counter": 20,
        "Step": 2
}
```

Now, they should have more information for a type resolution on deserialization by using a FullName from the type, along with the AssemblyName.

```
{
        "_t": "MyApplicationName.InternalState, MyApplicationName",
        "Counter": 20,
        "Step": 2
}
```

This should eliminate the need for registering each of your persisted object types with Mongo, like this:

```
BsonClassMap.LookupClassMap(typeof(InternalState));
```

### CODE REVIEW

**Comment by spankr** [comment]
One thing we discussed (that isn't addressed by this PR) are situations where persisted items get renamed (or the assembly gets renamed). It doesn't know how to resolve the types in that case.

We also noticed that in the case that we aren't able to deserialize items, nothing is sent to the logs to indicate a deserialization failure. I wanted to keep the scope of the PR small so I didn't try to address this one.

**Comment by spankr** [comment]
Hmm, I noticed that it's having an issue with Journal entries. I'm going to revoke the PR for the meantime.

**Comment by spankr** [comment]
Okay, its working fine. I'll reopen it. I just didn't want getting merged while I noticed something odd on my end.

**Comment by Aaronontheweb** [comment]
@spankr would you mind rebasing this on the latest? I changed the `.csproj` around some.

**Comment by spankr** [comment]
I'll leave myself a note and give the rebase a shot on Monday.

**Comment by spankr** [comment]
@Aaronontheweb  I merged in the latest dev branch. It doesn't appear to have had any merge issues.

I'm trying to build locally as a sanity check but I have to remember how to bypass the proxy. :)

**Comment by spankr** [comment]
Yeah, I pooched that with rolling in out of date .csproj changes.  👎

**Comment by jackowild** [comment]
@spankr Will this affect existing codebases that haven't used the full type name? Will they still recover events/snapshots and persist after this change?

**Comment by spankr** [comment]
@jackowild Yes, the goal when I first wrote this was for it to be backwards compatible. 

Now that there are tests in the project (and a ton of other good changes), I might have to do a little re-thinking.

**Comment by spankr** [comment]
Looks like it is working with backwards compatibility.  Just plugging in the change without modifying code (i.e. keeping in existing `BsonClassMap.LookupClassMap(...)` lines), the journals and snapshots will auto-correct (read in old persistence style, write out new persistence style).

After the new full typing is used in the DB, the references to `BsonClassMap.LookupClassMap(...)` are no longer required.

One additional feature that using full type discriminators allows is reuse of internal class names for messages. If different persistent actor classes have internal snapshot objects that reuse the same name:
```
BsonClassMap.LookupClassMap(typeof(PersistentActorOne.InternalState));
BsonClassMap.LookupClassMap(typeof(PersistentActorTwo.InternalState));
```

The existing serialization will fail with an ambiguous deserialization error because it cannot tell which class "InternalState" deserializes into.

**Comment by jackowild** [comment]
Is this ready to be merged in now then @spankr ?

**Comment by spankr** [comment]
@jackowild  Yes, I believe its back in a state now where the PR process can continue.

**Pull request merged**
