### PR TITLE
Update to Akka 1.3.5, MongoDB Driver to 2.5.0 and .NET Standard support

### PR DESCRIPTION
**Pull request by jackowild**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@jackowild don't forget to update the `RELEASE_NOTES.md` with the new version number! that gets written out to `common.props` build the `build.cmd` script, which is what gets used in the NuGet package versioning.

**Comment by jackowild** [comment]
@Aaronontheweb I was going to leave it with the version number you put in the other day, 1.3.5. Tell me if this is wrong please! As you can see there are conflicts so I need to sort them out first.

**Comment by Aaronontheweb** [comment]
Ah, nope - totally forgot I did that. Good to go then. Looks like you might need to rebase some of the changes here before they can merged into `master` though.

**Comment by jackowild** [comment]
Would you mind telling me exactly how to do this? I'm not too familiar with rebase. Do I fork dev then rebase to master there, then create a PR into master from that? Or can I rebase dev from AkkaNetContrib.

**Comment by Aaronontheweb** [comment]
@jackowild in a new branch derived from the current dev branch, do a `rebase master`. Once you get through all of the conflicts there and the thing still runs, push up that PR and merge it into `dev`. That should turn this PR green automatically.

**Comment by jackowild** [comment]
@Aaronontheweb OK I did this and can see duplicate commits now. Should I have done an interactive rebase and squashed the duplicate commits into 1? See https://github.com/jackowild/Akka.Persistence.MongoDB/commits/dev

**Comment by Aaronontheweb** [comment]
@jackowild I have this fixed on another PR; waiting on CI to run it and then I'll merge it in and this should kick off a master release, which I'll monitor while I work on some other stuff here.

**Comment by jackowild** [comment]
Great, thanks @Aaronontheweb

**Pull request merged**
